name: Build and Push Multi-Arch Docker Image

on:
  push:
    tags:
      - "*.*.*"
        

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  TAG: ${{ github.ref_name }}

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push (${{ matrix.ARCH }}-${{ matrix.OS }})
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  update-chart:
    runs-on: ubuntu-latest
    needs:
      - docker-build
    steps:
      - name: Trigger helm-charts update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow --repo ${{ github.repository_owner }}/helm-charts run update-chart.yaml -f APP_VERSION=${{ github.ref_name }} -f CHART_NAME=argocd-source-tracker
        
